import { InterviewGuide } from '../types';

export const DEFAULT_GUIDES: InterviewGuide[] = [
  {
    id: 'guia-oficial-unicordoba-ia',
    title: 'Inteligencia Artificial y Educación (UniCórdoba)',
    description: 'Una conversación abierta y reflexiva sobre cómo usas la IA en tus actividades académicas, dilemas éticos, vivencias en clase y propuestas de mejora.',
    targetPersona: 'Docentes en formación y estudiantes de la Licenciatura en Informática',
    institutionalContext: 'Universidad de Córdoba - Montería, Colombia',
    researchGoals: [
      'Identificar prácticas actuales y mediación pedagógica con herramientas de IA en el programa',
      'Analizar la dimensión ética, reflexiones sobre privacidad, derechos de autor y sesgos algorítmicos',
      'Examinar la articulación de saberes pedagógicos, tecnológicos y éticos en el currículo de la Licenciatura',
      'Evaluar el impacto de la IA en la planeación didáctica, autonomía y creatividad de los futuros educadores',
      'Identificar retos, barreras de infraestructura tecnológica, conectividad y falta de capacitación formal',
      'Recoger propuestas y estrategias formuladas por los estudiantes para enriquecer el plan de estudios',
    ],
    isTemplate: true,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q1',
        category: 'Inteligencia Artificial (IA)',
        subCategory: 'Gestión y mediación pedagógica',
        topic: 'Prácticas Actuales y Mediación Pedagógica con IA',
        question: '¿De qué manera incorporas herramientas de inteligencia artificial (como ChatGPT, Gemini, generadores de medios audiovisuales u otras) en tus actividades académicas y prácticas pedagógicas de la Licenciatura?',
        probingTips: 'Pregunta qué herramientas específicas utiliza, en qué asignaturas o proyectos formativos las ha empleado, con qué frecuencia y si los docentes formadores orientan su uso didáctico.',
        objectiveLink: 'Objetivo Específico 1: Identificar prácticas actuales relacionadas con el uso de la IA en la formación docente.',
      },
      {
        id: 'q2',
        category: 'Inteligencia Artificial (IA)',
        subCategory: 'Dimensión ética y crítica',
        topic: 'Conciencia Ética, Privacidad y Sesgos Algorítmicos',
        question: 'Al utilizar inteligencia artificial en tus labores académicas y pedagógicas, ¿qué consideraciones o precauciones tienes respecto a la privacidad de los datos, los derechos de autor y los posibles sesgos de estas herramientas?',
        probingTips: 'Indaga si han discutido estos dilemas éticos en clase, si verifica las fuentes de información que entrega la IA y cómo enseña a sus futuros alumnos a no depender ciegamente de estas tecnologías.',
        objectiveLink: 'Objetivo Específico 2: Describir percepciones y experiencias críticas de los estudiantes.',
      },
      {
        id: 'q3',
        category: 'Formación Docente',
        subCategory: 'Articulación de saberes (Pedagógico, Tecnológico y Ético)',
        topic: 'Integración Curricular de Saberes en la Licenciatura',
        question: 'En las asignaturas del programa de Licenciatura en Informática, ¿cómo consideras que se articulan los saberes pedagógicos con el conocimiento técnico de la inteligencia artificial? ¿Sientes que se enseña a usar la IA con sentido didáctico o solo como una herramienta técnica instrumental?',
        probingTips: 'Pide ejemplos de materias específicas donde se haya integrado la IA con la didáctica. Indaga si existe una formación estructurada o si depende de iniciativas individuales de cada docente.',
        objectiveLink: 'Objetivo Específico 2 y 3: Evaluar la formación en competencias pedagógicas y tecnológicas.',
      },
      {
        id: 'q4',
        category: 'Formación Docente',
        subCategory: 'Práctica Reflexiva',
        topic: 'Rol Docente y Desarrollo de la Práctica Reflexiva',
        question: '¿De qué manera el uso de la inteligencia artificial ha influido en tu capacidad para reflexionar sobre tu propia práctica pedagógica y sobre tu identidad como futuro licenciado en informática y medios audiovisuales?',
        probingTips: 'Profundiza en si la IA los lleva a cuestionar su rol en el aula, cómo median el aprendizaje frente a estudiantes que también usan IA, y si sienten que fortalece o debilita su pensamiento crítico.',
        objectiveLink: 'Objetivo Específico 3: Evaluar el desarrollo de competencias reflexivas y profesionales.',
      },
      {
        id: 'q5',
        category: 'Efectos de la IA',
        subCategory: 'Impacto en la práctica profesional (Planeación y Creatividad)',
        topic: 'Beneficios en la Planeación Didáctica y Recursos Audiovisuales',
        question: 'Al momento de diseñar clases, planear secuencias didácticas o crear recursos educativos y audiovisuales, ¿cuáles han sido los principales beneficios e impactos positivos que has experimentado al apoyarte en la inteligencia artificial?',
        probingTips: 'Pide que relate una experiencia concreta de planeación didáctica o creación de material audiovisual con IA que haya resultado exitosa o innovadora.',
        objectiveLink: 'Objetivo Específico 3: Evaluar los beneficios en competencias pedagógicas y creativas.',
      },
      {
        id: 'q6',
        category: 'Efectos de la IA',
        subCategory: 'Retos y limitaciones formativas',
        topic: 'Limitaciones, Infraestructura y Brechas en el Contexto Universitario',
        question: 'Pensando en tu contexto en la Universidad de Córdoba y tus prácticas, ¿cuáles han sido las mayores dificultades, limitaciones o vacíos que has enfrentado (por ejemplo, falta de capacitación formal, conectividad, laboratorios, resistencia de docentes o desinformación)?',
        probingTips: 'Indaga en el contexto regional (Montería, sedes o centros de tutoría), acceso a internet, equipos de cómputo en la universidad y la preparación de los docentes formadores.',
        objectiveLink: 'Objetivo Específico 3: Evaluar limitaciones y barreras contextuales en la Universidad de Córdoba.',
      },
      {
        id: 'q7',
        category: 'Efectos de la IA',
        subCategory: 'Propuesta de estrategias formativas',
        topic: 'Estrategias y Recomendaciones Curriculares para el Programa',
        question: 'Para concluir: desde tu experiencia como estudiante de la Licenciatura, ¿qué estrategias, talleres o cambios curriculares propondrías a la Universidad de Córdoba y al programa para fortalecer la formación pedagógica y ética en inteligencia artificial?',
        probingTips: 'Pregunta si propone electivas dedicadas, actualización de planes de curso, laboratorios de experimentación o lineamientos institucionales claros sobre el uso ético de la IA.',
        objectiveLink: 'Objetivo Específico 4: Proponer estrategias que fortalezcan la integración crítica de la IA en el programa.',
      },
    ],
  },
  {
    id: 'guia-docentes-formadores',
    title: 'Guion Complementario: Percepción Docente y Práctica Pedagógica',
    description: 'Protocolo enfocado en docentes formadores y egresados de la Licenciatura en Informática para triangular la información recolectada con la muestra estudiantil.',
    targetPersona: 'Docentes formadores de la Universidad de Córdoba / Egresados del programa',
    institutionalContext: 'Universidad de Córdoba - Montería',
    researchGoals: [
      'Contrastar la visión de los formadores con las experiencias de los estudiantes',
      'Analizar los desafíos institucionales para actualizar el currículo',
    ],
    isTemplate: true,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q1',
        category: 'Inteligencia Artificial (IA)',
        subCategory: 'Gestión y mediación pedagógica',
        topic: 'Adopción Didáctica de la IA',
        question: '¿Cómo valora usted la incorporación de la inteligencia artificial en la formación inicial docente en la Universidad de Córdoba?',
        probingTips: 'Pregunte sobre políticas de cátedra y orientaciones dadas a los estudiantes.',
      },
      {
        id: 'q2',
        category: 'Formación Docente',
        subCategory: 'Articulación de saberes',
        topic: 'Desafíos de Capacitación y Competencias',
        question: '¿Qué competencias pedagógicas y éticas considera indispensables desarrollar en los futuros licenciados para una integración consciente de la IA?',
        probingTips: 'Profundice en brecha generacional y resistencia al cambio tecnológico.',
      },
      {
        id: 'q3',
        category: 'Efectos de la IA',
        subCategory: 'Retos y limitaciones formativas',
        topic: 'Transformación Institucional y Curricular',
        question: '¿Qué acciones institucionales prioritarias considera necesarias en la Universidad de Córdoba para institucionalizar el uso crítico de la IA?',
        probingTips: 'Indague sobre infraestructura, investigación formativa y actualización curricular.',
      },
    ],
  },
];
